### ISSUE TITLE
"To Build" python 3 support

### ISSUE THREAD

**Issue by JoshZastrow** [arulrajnet/attila-demo#1]
#### To build
Clone the blog
```
git clone https://github.com/arulrajnet/attila-demo
cd attila-demo
git submodule update --init --recursive
git fetch --recurse-submodules
git pull --recurse-submodules
```

#### fabric commands
_**Commands do not work with Python 3**_
```
fab help
fab build
fab serve
```

Is there a way to build without using the fab commands? Thanks!

**Comment by arulrajnet** [comment]
Yes. You can do without using fab

*To build*

```
pelican -s pelicanconf.py
```

*To Serve*

```
pushd output; python -m SimpleHTTPServer; popd
```
Then http://localhost:8000

**Comment by arulrajnet** [comment]
You can also use this [Makefile](https://github.com/arulrajnet/attila-demo/blob/master/Makefile)

**Comment by arulrajnet** [comment]
@JoshZastrow Hope above solves your issue.
