### ISSUE TITLE
How to remove cover image?

### ISSUE THREAD

**Issue by trinhvv** [arulrajnet/attila-demo#4]
Hi,
I would like to know how to remove cover on the blog, like this one https://woobull.com?
Thanks a lot!
V.

**Comment by arulrajnet** [comment]
We don't support it. Because we forked from earlier version of attila. We have to sync with that latest version. That is tracked here https://github.com/arulrajnet/attila/issues/23 

[Header color](https://github.com/arulrajnet/attila#header-color) white|transparent may help you.

**Comment by trinhvv** [comment]
Thanks, I will try the header color white|transparent things.

**Comment by trinhvv** [comment]
The solution is simply specify a non-exist image.
