### ISSUE TITLE
outdated, e.g. not working with python3

### ISSUE THREAD

**Issue by kraxli** [arulrajnet/attila-demo#7]
Hi 

thanks for the nice template which I would love to use with Python3. Unfortunately, I get many errors in the `fabfile.py` related to Python2 vs Python3.

Building attila-demo with `make devserver` (with a newer `Makefile` generated by `pelican-quickstart`) generates the blog but the Menu is empty and the top-left "Home" button does not work. 

**Env**:

- Pelican 4.5
- tried Python 3.7 and 3.8 with the same results.
- Ubuntu 20.04

Thanks for your help!

**Comment by arulrajnet** [comment]
@kraxli Thanks for reporting. Will have look

**Comment by arulrajnet** [comment]
@kraxli updated the steps.
